name: Go

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: "false"

jobs:
  release:
    name: Build and Release ${{ matrix.target_os }}_${{ matrix.target_arch }} binaries
    runs-on: ${{ matrix.runner }}
    env:
      GOVER: ${{ matrix.go-version }}
      GOLANGCILINT_VER: v1.45
      GOOS: ${{ matrix.target_os }}
      GOARCH: ${{ matrix.target_arch }}
      GOPROXY: https://proxy.golang.org
      ARCHIVE_OUTDIR: dist/archives
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        go-version: [1.17.6]
        include:
          # Specify default runner for all ubuntu
          - { os: ubuntu-latest, runner: ubuntu-latest }

          # Specify default runner for all MacOS
          - { os: macOS-latest, runner: macOS-latest }

          # Specify target_os names for all systems
          - { os: ubuntu-latest, target_os: linux }
          - { os: macOS-latest, target_os: darwin }

          # Specify target_arch for ubuntu
          - { os: ubuntu-latest, target_arch: arm }
          - { os: ubuntu-latest, target_arch: arm64 }

          # Specify target_arch for MacOS amd64
          - { os: macOS-latest, target_arch: amd64 }

          # Add specific runner for MacOS arm64
          - {
              os: macOS-latest,
              runner: M1,
              target_os: darwin,
              target_arch: arm64,
            }

    steps:
      - uses: actions/checkout@main
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version

      - name: Cache Go modules (Linux)
        if: matrix.target_os == 'linux'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ matrix.target_os }}-${{ matrix.target_arch }}-go-${{ env.GOVER }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.target_os }}-${{ matrix.target_arch }}-go-${{ env.GOVER }}-build-
      - name: Cache Go modules (macOS)
        if: matrix.target_os == 'darwin'
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ matrix.target_os }}-${{ matrix.target_arch }}-go-${{ env.GOVER }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.target_os }}-${{ matrix.target_arch }}-go-${{ env.GOVER }}-build-

      - name: Set up Honeycomb Otel from Github Secret
        run: |
          mkdir -p $HOME/.bacalhau
          echo "${{ secrets.HONEYCOMB_OTEL_KEY }}" >> $HOME/.bacalhau/config.toml

      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.11
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: golangci-lint
        if: matrix.target_arch == 'amd64' && matrix.target_os == 'linux'
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: ${{ env.GOLANGCILINT_VER }}

      - name: Run go mod tidy check diff
        if: matrix.target_arch == 'amd64' && matrix.target_os == 'linux'
        run: make modtidy check-diff

      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.11
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Build
        run: make build

      - name: Install IPFS
        run: |
          curl -O https://dist.ipfs.io/go-ipfs/v0.12.2/go-ipfs_v0.12.2_${{ matrix.target_os }}-${{ matrix.target_arch }}.tar.gz
          tar -xvzf go-ipfs_v0.12.2_${{ matrix.target_os }}-${{ matrix.target_arch }}.tar.gz
          cd go-ipfs
          sudo bash install.sh

      - name: Test
        if: matrix.target_arch == 'amd64' && matrix.target_os == 'linux'
        run: make test
