name: Go

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: "false"

jobs:
  build:
    name: Build ${{ matrix.target_os }}_${{ matrix.target_arch }} binaries
    runs-on: ${{ matrix.runner }}
    env:
      GOVER: ${{ matrix.go_version }}
      GOLANGCILINT_VER: v1.46
      GOOS: ${{ matrix.target_os }}
      GOARCH: ${{ matrix.target_arch }}
      GOPROXY: https://proxy.golang.org
      ARCHIVE_OUTDIR: dist/archives
    strategy:
      fail-fast: false
      matrix:
        # GitHub Actions does not yet support Arm or Arm64
        # name: [macOS-arm64, macOS-amd64, ubuntu-arm, ubuntu-arm64, ubuntu-amd64]
        name: [macOS-arm64, macOS-amd64, ubuntu-amd64]
        go_version: [1.18.3]
        include:
        - {
            name: ubuntu-amd64,
            os: ubuntu-latest,
            target_os: linux,
            runner: ubuntu-latest,
            target_arch: amd64,
          }
    steps:
      - uses: actions/checkout@main
      
      - name: Set up Honeycomb Otel from Github Secret
        run: |
          echo "${{ secrets.HONEYCOMB_OTEL_KEY }}" >> $HOME/secrets_tmp
          echo "${{ secrets.APPLE_DEVELOPER_ID_PASSWORD }}" >> secrets.txt
          echo "${{ secrets.GOOGLE_APPLICATION_DEVELOPMENT_CREDENTIALS }}" >> secrets.txt
          echo "${{ secrets.GOOGLE_APPLICATION_DEVELOPMENT_SA_EMAIL }}" >> secrets.txt
          echo "${{ secrets.GOOGLE_APPLICATION_DEVELOPMENT_SA_KEYI }}" >> secrets.txt
          echo "${{ secrets.HONEYCOMB_OTEL_KEY }}" >> secrets.txt
          echo "${{ secrets.MACOS_CERTIFICATE }}" >> secrets.txt
          echo "${{ secrets.MACOS_CERTIFICATE_PWD }}" >> secrets.txt
          echo "${{ secrets.PRIVATE_KEY_PASSPHRASE }}" >> secrets.txt
          echo "${{ secrets.PRIVATE_PEM }}" >> secrets.txt
          echo "${{ secrets.PUBLIC_PEM }}" >> secrets.txt


      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.11
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
